version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./website/:/code/website/

  redis:
    image: "redis:6.0.16"

  db:
    image: "postgres:14.1"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_db
