# Generated by Django 3.2.11 on 2022-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20220113_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=60),
        ),
    ]
