# Generated by Django 3.2.11 on 2022-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtask',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflow'),
        ),
    ]
