# Generated by Django 3.2.11 on 2022-01-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflowtask_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
